# Generated by Django 5.0.3 on 2024-03-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login',
            field=models.TextField(default=0, max_length=100),
        ),
    ]
